// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListDAL;

namespace ShoppingListDAL.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20201022231500_SeedProductsData")]
    partial class SeedProductsData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingListDAL.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GTFO",
                            Price = 27.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Among Us",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phasmophobia",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hades",
                            Price = 24.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
